Update openwrt-ci.yml

diff --git a/.github/workflows/openwrt-ci.yml b/.github/workflows/openwrt-ci.yml
--- a/.github/workflows/openwrt-ci.yml
+++ b/.github/workflows/openwrt-ci.yml
@@ -1,88 +1,98 @@
-name: OpenWrt K2P CI
-on:
+#修改TNAME: K2P-5.0 中的K2P-5.0为你需要编译的型号，注意名称要与configs/templates/目录下的名字相同
+name: Build Padavan
+
+on: 
   release:
-    types: [created]
+    types: [published]
+  push:
+    tags:
+    - 'v*'
+    branches: 
+      - master
+  schedule:
+    - cron: 0 8 * * 5
+  watch:
+    types: [started]
+
 jobs:
   build:
     runs-on: ubuntu-18.04
-    env:
-      VERSION: 18.06.6
-      URL: https://github.com/openwrt/openwrt/archive/v18.06.6.tar.gz
-    steps:
-    - name: Checkout - clone repository
-      uses: actions/checkout@v1
-    - name: Install - system build dependencies
-      run: sudo apt install subversion build-essential libncurses5-dev zlib1g-dev gawk git ccache gettext libssl-dev xsltproc zip
-    - name: Download - openwrt source download
-      run: |
-        wget $URL
-        tar -zxf v$VERSION.tar.gz
-    - name: Update - openwrt source update
-      run: |
-        cd openwrt-$VERSION
-        ./scripts/feeds update -a
-    - name: Install - openwrt source install
-      run: |
-        cd openwrt-$VERSION
-        ./scripts/feeds install -a
-    - name: Delete - delete openwrt shadowsocks
-      run: |
-        cd openwrt-$VERSION
-        rm -rf feeds/luci/applications/luci-app-shadowsocks-libev/luasrc/controller/shadowsocks-libev.lua
-        rm -rf feeds/luci/applications/luci-app-shadowsocks-libev/luasrc/model/shadowsocks-libev.lua
-        rm -rf feeds/luci/applications/luci-app-shadowsocks-libev/root/etc/uci-defaults/40_luci-shadowsocks-libev
-        rm -rf feeds/luci.tmp/info/.packageinfo-applications_luci-app-shadowsocks-libev
-        rm -rf feeds/packages/net/shadowsocks-libev/files/shadowsocks-libev.config
-        rm -rf feeds/packages/net/shadowsocks-libev/files/shadowsocks-libev.init
-        rm -rf feeds/packages.tmp/info/.packageinfo-net_shadowsocks-client
-        rm -rf feeds/packages.tmp/info/.packageinfo-net_shadowsocks-libev
-        rm -rf package/feeds/luci/luci-app-shadowsocks-libev
-        rm -rf package/feeds/packages/shadowsocks-client
-        rm -rf package/feeds/packages/shadowsocks-libev
-    - name: Clone - openwrt plugin source
-      run: |
-        cd openwrt-$VERSION
-        git clone https://github.com/pymumu/smartdns.git ../smartdns
-        cp -r ../smartdns/package/openwrt/ ./package/smartdns
-        git clone -b openwrt-18.06 https://github.com/rosywrt/luci-theme-rosy.git package/luci-theme-rosy
-        git clone https://github.com/LGA1150/openwrt-fullconenat package/fullconenat
-        git clone https://github.com/honwen/luci-app-aliddns.git package/luci-app-aliddns
-        git clone https://github.com/trojan-gfw/openwrt-trojan.git package/openwrt-trojan
-        git clone https://github.com/qq523407234/openwrt-udp2raw.git package/openwrt-udp2raw
-        git clone https://github.com/qq523407234/luci-app-udp2raw.git package/luci-app-udp2raw
-        git clone https://github.com/shadowsocks/luci-app-shadowsocks.git package/luci-app-shadowsocks
-        git clone https://github.com/shadowsocks/openwrt-shadowsocks.git package/openwrt-shadowsocks
-        git clone https://github.com/thisdk/luci-app-vlmcsd.git package/luci-app-vlmcsd
-        git clone https://github.com/thisdk/luci-app-smartdns.git package/luci-app-smartdns
-        git clone https://github.com/thisdk/openwrt-vlmcsd.git package/openwrt-vlmcsd
-        git clone https://github.com/thisdk/openwrt-simple-obfs.git package/openwrt-simple-obfs
-        git clone https://github.com/thisdk/openwrt-v2ray-plugin.git package/openwrt-v2ray-plugin
-        git clone https://github.com/thisdk/k2p-openwrt-mt7615_5.0.2.0.git package/k2p-openwrt-mt7615_5.0.2.0
-    - name: Config - copy k2p build config
-      run: cp ./.config.18.06.6.release openwrt-$VERSION/.config
-    - name: Download - openwrt build dependencies
-      run: |
-        cd openwrt-$VERSION
-        make download -j10
-    - name: Build - make openwrt source
-      run: |
-        cd openwrt-$VERSION
-        make -j4
-    - name: Remove - delete packages files
-      run: |
-        cd openwrt-$VERSION/bin/targets/ramips/mt7621/
-        rm -rf packages/
-        ls -hl
-    - name: Release - push to release file
-      uses: softprops/action-gh-release@v1
-      if: startsWith(github.ref, 'refs/tags/')
-      with:
-        files: openwrt-${{ env.VERSION }}/bin/targets/ramips/mt7621/*
-      env:
-        GITHUB_TOKEN: ${{ secrets.RELEASES_DEPLOY_TOKEN }}
-    - name: Upload - push to artifact file
-      uses: actions/upload-artifact@v1
-      with:
-        name: openwrt-k2p
-        path: openwrt-${{ env.VERSION }}/bin/targets/ramips/mt7621/
 
+    steps:
+    - name: Checkout
+      uses: actions/checkout@master
+    - name: Initialization environment
+      env:
+        DEBIAN_FRONTEND: noninteractive
+      run: |
+        #sudo apt-get update
+        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
+        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
+        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev gcc-multilib
+    - name: Clone source code
+      run: |
+        git clone --depth=1 https://github.com/chongshengB/rt-n56u.git /opt/rt-n56u
+        cd /opt/rt-n56u/toolchain-mipsel
+        mkdir -p toolchain-3.4.x
+        wget https://github.com/hanwckf/padavan-toolchain/releases/download/v1.0/mipsel-linux-uclibc.tar.xz
+        tar -xvf mipsel-linux-uclibc.tar.xz -C toolchain-3.4.x
+        mkdir -p /opt/images/
+    - name: Build Firmware
+      env:
+        TNAME: K2P-1.1
+      run: |
+        cd /opt/rt-n56u/trunk
+        if [ ! -f configs/templates/$TNAME.config ] ; then
+        echo "configs/templates/$TNAME.config not found "
+        exit 1
+        fi
+        cp -f configs/templates/$TNAME.config .config
+        ################################################################################################
+        #因不同型号配置功能不一样，所以先把配置项删除，如果你自己要添加其他的，也要写上删除这一条，切记！！！
+        ################################################################################################
+        sed -i '/CONFIG_FIRMWARE_INCLUDE_MENTOHUST/d' .config #删除配置项MENTOHUST
+        sed -i '/CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT/d' .config #删除配置项SCUTCLIENT
+        sed -i '/CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS/d' .config #删除配置项SS plus+
+        sed -i '/CONFIG_FIRMWARE_INCLUDE_SSSERVER/d' .config #删除配置项SS server
+        sed -i '/CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER/d' .config #删除配置项DNSFORWARDER
+        sed -i '/CONFIG_FIRMWARE_INCLUDE_ADBYBY/d' .config #删除配置项adbyby plus+
+        sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPC/d' .config #删除配置项adbyby plus+
+        sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPS/d' .config #删除配置项adbyby plus+
+        sed -i '/CONFIG_FIRMWARE_INCLUDE_TUNSAFE/d' .config #删除配置项adbyby plus+
+        sed -i '/CONFIG_FIRMWARE_INCLUDE_ALIDDNS/d' .config #删除配置项阿里DDNS
+        sed -i '/CONFIG_FIRMWARE_INCLUDE_SMARTDNS/d' .config
+        ######################################################################
+        #以下选项是定义你需要的功能（y=集成,n=忽略），重新写入到.config文件
+        ######################################################################
+        echo "CONFIG_FIRMWARE_INCLUDE_MENTOHUST=n" >> .config #MENTOHUST
+        echo "CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT=n" >> .config #SCUTCLIENT
+        echo "CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=y" >> .config #SS plus+
+        echo "CONFIG_FIRMWARE_INCLUDE_SSSERVER=n" >> .config #SS server
+        echo "CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER=n" >> .config #DNSFORWARDER
+        echo "CONFIG_FIRMWARE_INCLUDE_ADBYBY=y" >> .config #adbyby plus+
+        echo "CONFIG_FIRMWARE_INCLUDE_FRPC=n" >> .config #内网穿透FRPC
+        echo "CONFIG_FIRMWARE_INCLUDE_FRPS=n" >> .config #内网穿透FRPS
+        echo "CONFIG_FIRMWARE_INCLUDE_TUNSAFE=n" >> .config #TUNSAFE
+        echo "CONFIG_FIRMWARE_INCLUDE_ALIDDNS=y" >> .config #阿里DDNS
+        echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNS=y" >> .config #smartdns
+        echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNSBIN=y" >> .config #smartdns二进制文件
+        echo "CONFIG_FIRMWARE_INCLUDE_V2RAY=n" >> .config #集成v2ray执行文件，如果不集成，会从网上下载下来执行，不影响正常使用
+        echo "CONFIG_FIRMWARE_INCLUDE_TROJAN=n" >> .config #集成trojan执行文件，如果不集成，会从网上下载下来执行，不影响正常使用
+        echo "CONFIG_FIRMWARE_INCLUDE_KOOLPROXY=y" >> .config #KP广告过滤
+        echo "CONFIG_FIRMWARE_INCLUDE_CADDY=y" >> .config #在线文件管理服务
+        echo "CONFIG_FIRMWARE_INCLUDE_CADDYBIN=n" >> .config #集成caddu执行文件，此文件有13M,请注意固件大小。如果不集成，会从网上下载下来执行，不影响正常使用
+        #########################################################################################
+        #自定义添加其它功能请参考源码configs/templates/目录下的config文件。按照上面的格式添加即可
+        #格式如下：
+        #sed -i '/自定义项/d' .config
+        #echo "自定义项=y" >> .config
+        #########################################################################################
+        sudo ./clear_tree
+        sudo ./build_firmware_bkye $TNAME
+        sudo mv -f images/*.trx /opt/images/
+    - name : Upload packages
+      uses: actions/upload-artifact@master
+      if: always()
+      with:
+        name: Padavan-packages
+        path: /opt/images
